name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "lint | ${{ matrix.php-version }} / drupal/core:${{ matrix.drupal }}"
    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3' ]
        drupal: [ '^10' ]
        include:
          - php-version: "8.3"
            drupal: "^11.1"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd
          coverage: none
          tools: composer:v2

      - name: "Set drupal/core to ${{ matrix.drupal }}"
        run: "composer require drupal/core:${{ matrix.drupal }} --no-update"
      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
      - name: PHPCS
        run: php vendor/bin/phpcs
      - name: PHPStan
        run: php vendor/bin/phpstan analyze
  test:
    runs-on: ubuntu-latest
    name: "test | ${{ matrix.php-version }} / drupal/core:${{ matrix.drupal }}"
    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3' ]
        drupal: [ '^10' ]
        include:
          - php-version: "8.3"
            drupal: "^11.1"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gd
          coverage: none
          tools: composer:v2

      - name: "Set drupal/core to ${{ matrix.drupal }}"
        run: "composer require drupal/core:${{ matrix.drupal }} --no-update"
      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
      - name: phpunit
        run: php vendor/bin/phpunit
